### ISSUE TITLE
Undefined offset warning when block displays odd number of briefings

### ISSUE THREAD

**Issue by simoncoggins** [cruciux/ap-moodle-block#2]
I noticed I get:

Notice: Undefined offset: 1 in /Users/simonc/code/totara/blocks/anderspink/block_anderspink.php on line 208

when the block returns an odd number of briefings. This is due to this line:

https://github.com/anderspink/moodle-block_anderspink/blob/master/block_anderspink.php#L208

failing to check the array key exists before displaying.

Adding a check would remove the error but I wonder if it would be better to use floating divs and rely on native float behaviour to wrap additional divs?

**Comment by cruciux** [comment]
Thanks, fixed by 5cbfa2c

I was scared of using slightly more modern css with the even/odd selectors, but from browser compatibilities it looks fine!
