### ISSUE TITLE
Minor: Spelling Mistake With boolean

### ISSUE THREAD

**Issue by christopher-learningpool** [cruciux/ap-moodle-block#5]
https://github.com/anderspink/moodle-block_anderspink/blob/caa8dccbfa8d8970146af497a661c7c594c2d98a/block_anderspink.php#L37

**Expected**
$content_preview=false

**Actual**
$content_preview=fale

**Comment by cruciux** [comment]
ahh whoops, thanks will fix shortly!

**Comment by cruciux** [comment]
fixed by 9fe8a1cafd9a1f0248ae9a72a7200aefee941281
